# Generated by Django 3.2.7 on 2021-09-12 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator])),
            ],
        ),
    ]
